import { StyleSheet } from "react-native"
import { colors } from "./theme"

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.paper },
  safeDark: { backgroundColor: "#18221d" },
  fill: { flex: 1 },
  page: { width: "100%", maxWidth: 560, alignSelf: "center", paddingHorizontal: 25, paddingTop: 12, paddingBottom: 40 },
  topline: { height: 52, flexDirection: "row", alignItems: "center", marginBottom: 37 },
  logoMark: { width: 34, height: 34, borderRadius: 11, backgroundColor: colors.green, alignItems: "center", justifyContent: "center", marginRight: 9 },
  logoPhoto: { width: 21, height: 25, borderRadius: 4, backgroundColor: colors.white, overflow: "hidden", position: "relative" },
  logoSun: { position: "absolute", width: 5, height: 5, top: 4, right: 4, borderRadius: 3, backgroundColor: colors.orange },
  logoHillBack: { position: "absolute", width: 14, height: 9, left: 0, bottom: 0, borderTopRightRadius: 9, backgroundColor: "#a7b899", transform: [{ rotate: "-8deg" }] },
  logoHillFront: { position: "absolute", width: 12, height: 7, right: -1, bottom: 0, borderTopLeftRadius: 8, backgroundColor: colors.green, transform: [{ rotate: "8deg" }] },
  brand: { fontSize: 11, letterSpacing: 1.7, fontWeight: "700", color: colors.ink },
  round: { marginLeft: "auto", fontSize: 9, letterSpacing: 1.2, color: colors.muted, fontWeight: "700" },
  settingsIcon: { color: colors.green, fontSize: 18, marginLeft: 12 },
  heroCopy: { marginBottom: 24 },
  eyebrow: { color: colors.green, fontSize: 10, letterSpacing: 1.8, fontWeight: "700", marginBottom: 11 },
  title: { color: colors.ink, fontSize: 39, lineHeight: 43, letterSpacing: -1.3, fontFamily: "Georgia", marginBottom: 12 },
  body: { color: colors.muted, fontSize: 14, lineHeight: 21, marginBottom: 22, maxWidth: 390 },
  previewCard: { backgroundColor: colors.white, borderRadius: 19, padding: 10, marginBottom: 21, borderWidth: 1, borderColor: colors.line },
  previewImage: { height: 172, borderRadius: 12, overflow: "hidden", backgroundColor: "#d8dfcf", justifyContent: "flex-end", padding: 16 },
  previewSun: { position: "absolute", right: 24, top: 16, color: "#f2be73", fontSize: 39 },
  hillOne: { position: "absolute", height: 100, bottom: 0, left: -30, right: 110, borderTopRightRadius: 90, backgroundColor: "#93a88e", transform: [{ rotate: "-9deg" }] },
  hillTwo: { position: "absolute", height: 80, bottom: -26, left: 65, right: -28, borderTopLeftRadius: 90, backgroundColor: "#617e68", transform: [{ rotate: "-8deg" }] },
  previewCaption: { color: colors.white, fontSize: 12, fontWeight: "600", zIndex: 1 },
  previewDetails: { flexDirection: "row", alignItems: "center", paddingHorizontal: 7, paddingTop: 14, paddingBottom: 5 },
  miniLabel: { color: colors.muted, fontSize: 8, letterSpacing: 1.1, fontWeight: "700", marginBottom: 5 },
  hiddenValue: { color: colors.ink, fontSize: 14, letterSpacing: 1.5 },
  previewDivider: { height: 30, width: 1, backgroundColor: colors.line, marginHorizontal: 16 },
  lock: { marginLeft: "auto", width: 29, height: 29, borderRadius: 15, backgroundColor: "#edf1e9", alignItems: "center", justifyContent: "center" },
  lockText: { color: colors.green, fontSize: 14 },
  featureRow: { flexDirection: "row", marginBottom: 14, alignItems: "flex-start" },
  featureNumber: { color: colors.orange, fontSize: 10, fontWeight: "700", letterSpacing: 0.8, width: 33, paddingTop: 2 },
  featureText: { color: colors.ink, fontSize: 12, lineHeight: 18, flex: 1 },
  button: { backgroundColor: colors.green, minHeight: 55, borderRadius: 14, alignItems: "center", justifyContent: "center", marginTop: 12 },
  buttonDisabled: { opacity: 0.45 },
  buttonText: { color: "white", fontSize: 14, fontWeight: "700", letterSpacing: 0.25 },
  footnote: { textAlign: "center", fontSize: 8, letterSpacing: 1.2, color: colors.muted, marginTop: 17 },
  playerList: { marginTop: 8 },
  playerInputRow: { flexDirection: "row", alignItems: "center", borderBottomWidth: 1, borderColor: colors.line },
  playerIndex: { width: 43, color: colors.orange, fontWeight: "700", fontSize: 11 },
  input: { height: 55, flex: 1, fontSize: 16, color: colors.ink },
  addPlayer: { paddingVertical: 17 },
  addText: { color: colors.green, fontWeight: "700", fontSize: 13 },
  albumBox: { backgroundColor: colors.white, borderRadius: 13, paddingHorizontal: 14, paddingVertical: 12, borderWidth: 1, borderColor: colors.line, marginBottom: 12 },
  albumHeading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  albumFilterRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingTop: 12 },
  albumName: { color: colors.ink, fontSize: 13, fontWeight: "600" },
  albumOption: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 12, borderTopWidth: 1, borderColor: colors.line },
  albumSelect: { flex: 1 },
  albumActions: { flexDirection: "row", alignItems: "center", gap: 12, marginLeft: 10 },
  starText: { color: colors.orange, fontSize: 19 },
  albumActionText: { color: colors.muted, fontSize: 9, fontWeight: "700" },
  albumOptionName: { color: colors.ink, fontSize: 12 },
  albumCount: { color: colors.muted, fontSize: 10, marginLeft: 8 },
  permissionNote: { flexDirection: "row", padding: 14, backgroundColor: "#e9ede5", borderRadius: 13, marginTop: 9, marginBottom: 15 },
  noteIcon: { color: colors.green, fontSize: 15, marginRight: 10, marginTop: 1 },
  noteText: { flex: 1, color: colors.muted, fontSize: 11, lineHeight: 17 },
  error: { color: "#a44833", fontSize: 12, lineHeight: 17, marginVertical: 8 },
  spinner: { marginTop: 14 },
  back: { alignItems: "center", padding: 17 },
  backText: { color: colors.muted, fontSize: 12, fontWeight: "600" },
  settingsCard: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line, borderRadius: 15, padding: 16, marginBottom: 18 },
  settingRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 13, borderBottomWidth: 1, borderColor: colors.line },
  photoActions: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", minHeight: 34 },
  volumeControls: { flexDirection: "row", gap: 18 },
  photoFrame: { height: 300, overflow: "hidden", borderRadius: 17, backgroundColor: "#e4e5de", marginVertical: 8, position: "relative" },
  photo: { width: "100%", height: "100%" },
  photoTag: { position: "absolute", left: 12, bottom: 12, backgroundColor: "rgba(30,43,37,0.82)", borderRadius: 7, paddingVertical: 7, paddingHorizontal: 9 },
  photoTagText: { color: "white", fontSize: 8, letterSpacing: 1.1, fontWeight: "700" },
  fieldLabel: { color: colors.muted, fontSize: 9, letterSpacing: 1.2, fontWeight: "700", marginTop: 14, marginBottom: 6 },
  answerInput: { backgroundColor: colors.white, borderColor: colors.line, borderWidth: 1, borderRadius: 12, paddingHorizontal: 14, height: 49, color: colors.ink, fontSize: 14, justifyContent: "center" },
  dateHint: { color: "#a44833", fontSize: 10, marginTop: 5 },
  turnCount: { color: colors.muted, textAlign: "center", fontSize: 8, letterSpacing: 1.2, marginTop: 18 },
  answerCard: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line, borderRadius: 15, padding: 17, marginTop: 9, marginBottom: 22 },
  answerTitle: { color: colors.ink, fontSize: 23, fontFamily: "Georgia", marginBottom: 14 },
  answerPlace: { color: colors.ink, fontSize: 14, fontWeight: "600" },
  hostHint: { color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 12 },
  sectionLabel: { color: colors.muted, fontSize: 9, letterSpacing: 1.4, fontWeight: "700", marginBottom: 7 },
  resultRow: { flexDirection: "row", alignItems: "center", paddingVertical: 10, borderBottomWidth: 1, borderColor: colors.line },
  resultInitial: { width: 34, height: 34, borderRadius: 17, backgroundColor: "#e3e9df", alignItems: "center", justifyContent: "center", marginRight: 10 },
  initialText: { color: colors.green, fontWeight: "700" },
  resultInfo: { flex: 1 },
  resultName: { color: colors.ink, fontSize: 12, fontWeight: "700" },
  resultGuess: { color: colors.muted, fontSize: 10, marginTop: 3 },
  scoreBreakdown: { color: colors.green, fontSize: 9, marginTop: 3, fontWeight: "600" },
  judgeButton: { borderWidth: 1, borderColor: colors.line, borderRadius: 9, paddingHorizontal: 8, paddingVertical: 7 },
  judgeSelected: { backgroundColor: "#e2ece0", borderColor: colors.green },
  judgeText: { color: colors.muted, fontSize: 9, fontWeight: "700" },
  judgeTextSelected: { color: colors.green },
  scoreRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 8, borderBottomWidth: 1, borderColor: colors.line },
  totalScore: { color: colors.green, fontSize: 14, fontWeight: "700" },
  scoreNote: { color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 12, marginBottom: 7 },
})
